name: "BDS Test"

on: [push]

jobs:
  ## Windows tests
  Windows:
    runs-on: windows-latest
    strategy:
      matrix:
        ## Fetch BDS versions via Wayback Machine: https://web.archive.org/web/*/https://www.minecraft.net/en-us/download/server/bedrock
        ## minecraft-version: ["1.17.2.01", "1.17.11.01", "1.17.34.02", "1.17.41.01", "1.18.2.03", "1.18.12.01", "1.18.33.02", "1.19.1.01", "1.19.10.20"]
        ## python-version: ["3.10"]
        minecraft-version: ["1.19.2.02"]
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v3

      ## Start installing
      - name: Install Node dependencies
        run: npm install

      # This workflow will install Python dependencies, run tests and lint with a variety of Python versions
      # For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install Python dependencies
        run: |
          if (Test-Path -Path requirements.txt -PathType Leaf) {
            python -m pip install --upgrade pip
            pip install -r requirements.txt
          }

      - name: Download & Install Bedrock Server ${{ matrix.minecraft-version }}
        run: |
          Out-File -FilePath .\bds\version.json -InputObject `"${{ matrix.minecraft-version }}`" -Encoding ASCII
          curl --output bedrock_server.zip https://minecraft.azureedge.net/bin-win/bedrock-server-${{ matrix.minecraft-version }}.zip
          python ./bds/extract.pyc
          node bds/startServer.js -write=false -ignoreConfig
        working-directory: ./

      - name: Copy Minecraft packs
        run: python ./bds/copy.pyc

      - name: Enable all experimental features (world settings)
        run: |
        python ./bds/level_dat.pyc
        node bds/gametest.js

      ## BDS
      - name: Start Bedrock Server
        run: node bds/startServer.js
      
      - name: Content log check
        run: node bds/contentlog.js
  
  ## Linux test
  Ubuntu:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ## Fetch BDS versions via Wayback Machine: https://web.archive.org/web/*/https://www.minecraft.net/en-us/download/server/bedrock
        ## minecraft-version: ["1.17.2.01", "1.17.11.01", "1.17.34.02", "1.17.41.01", "1.18.2.03", "1.18.33.02", "1.19.1.01", "1.19.10.20"]
        ## python-version: ["3.10"]
        minecraft-version: ["1.19.2.02"]
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v3

      ## Start installing
      - name: Install Node dependencies
        run: npm install

      # This workflow will install Python dependencies, run tests and lint with a variety of Python versions
      # For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install Python dependencies
        run: |
          if [ -f "requirements.txt" ]
          then
            python -m pip install --upgrade pip
            pip install -r requirements.txt
          fi

      - name: Download & Install Bedrock Server ${{ matrix.minecraft-version }}
        run: |
          echo "\"${{ matrix.minecraft-version }}"\" > ./bds/version.json
          sudo apt-get install wget
          sudo apt-get install unzip
          wget -O bedrock_server.zip https://minecraft.azureedge.net/bin-linux/bedrock-server-${{ matrix.minecraft-version }}.zip
          unzip ./bedrock_server.zip -d bedrock_server
          node ./bds/startServer-linux.js -write=false -ignoreConfig
      
      - name: Copy Minecraft packs
        run: python ./bds/copy.pyc

      - name: Enable all experimental features (world settings)
        run: |
          python ./bds/level_dat.pyc
          node bds/gametest.js

      ## BDS
      - name: Start Bedrock Server
        run: node bds/startServer-linux.js
      
      - name: Content log check
        run: node bds/contentlog-linux.js
